[[main]]
  name = "棣栭〉"
  pageRef = "/"
  weight = 10

[[main]]
  name = "鏂囩珷"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "鏍囩"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "鍏充簬"
  pageRef = "about"
  weight = 40

[[footer]]
  name = "鏍囩"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "鍏充簬"
  pageRef = "about"
  weight = 20